services:
  # Node.js SSR Application
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: teaforms-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 3000
      AWS_REGION: local
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      DDB_TABLE: app_core
      DDB_ENDPOINT: http://dynamodb:8000
      COGNITO_USER_POOL_ID: local_pool_123
      COGNITO_CLIENT_ID: local_client_456
      JWT_ROLE_CLAIM: custom:role
      REDIS_URL: redis://redis:6379
      LOCAL_DEVELOPMENT: true
    depends_on:
      - dynamodb
      - redis
      # - localstack
    networks:
      - teaforms-network
    command: yarn dev:docker

  # DynamoDB Local
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: teaforms-dynamodb
    ports:
      - "8000:8000"
    volumes:
      - dynamodb-data:/data
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    networks:
      - teaforms-network

  # Redis for sessions
  redis:
    image: redis:7-alpine
    container_name: teaforms-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - teaforms-network

  # LocalStack for AWS services simulation (disabled temporarily)
  # localstack:
  #   image: localstack/localstack:latest
  #   container_name: teaforms-localstack
  #   ports:
  #     - "4566:4566"
  #     - "4571:4571"
  #   environment:
  #     - SERVICES=cognito-idp,s3,ses
  #     - DEBUG=1
  #     - DATA_DIR=/tmp/localstack/data
  #     - LAMBDA_EXECUTOR=local
  #     - HOSTNAME_EXTERNAL=localstack
  #     - AWS_DEFAULT_REGION=eu-west-2
  #   volumes:
  #     - localstack-data:/tmp/localstack
  #     - ./scripts/localstack:/docker-entrypoint-initaws.d
  #   networks:
  #     - teaforms-network

  # DynamoDB Admin UI (optional, for debugging)
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: teaforms-dynamodb-admin
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
      AWS_REGION: local
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb
    networks:
      - teaforms-network

networks:
  teaforms-network:
    driver: bridge

volumes:
  dynamodb-data:
  redis-data:
  localstack-data: